In [138]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [139]:
df = pd.read_csv('50_Startups.csv',index_col=0)
df

Administration  Marketing Spend       State     Profit
R&D Spend                                                        
165349.20       136897.80        471784.10    New York  192261.83
162597.70       151377.59        443898.53  California  191792.06
153441.51       101145.55        407934.54     Florida  191050.39
144372.41       118671.85        383199.62    New York  182901.99
142107.34        91391.77        366168.42     Florida  166187.94
131876.90        99814.71        362861.36    New York  156991.12
134615.46       147198.87        127716.82  California  156122.51
130298.13       145530.06        323876.68     Florida  155752.60
120542.52       148718.95        311613.29    New York  152211.77
123334.88       108679.17        304981.62  California  149759.96
101913.08       110594.11        229160.95     Florida  146121.95
100671.96        91790.61        249744.55  California  144259.40
93863.75        127320.38        249839.44     Florida  141585.52
91992.39        135495.07        252664.93  California  134307.35
119943.24       156547.42        256512.92     Florida  132602.65
114523.61       122616.84        261776.23    New York  129917.04
78013.11        121597.55        264346.06  California  126992.93
94657.16        145077.58        282574.31    New York  125370.37
91749.16        114175.79        294919.57     Florida  124266.90
86419.70        153514.11             0.00    New York  122776.86
76253.86        113867.30        298664.47  California  118474.03
78389.47        153773.43        299737.29    New York  111313.02
73994.56        122782.75        303319.26     Florida  110352.25
67532.53        105751.03        304768.73     Florida  108733.99
77044.01         99281.34        140574.81    New York  108552.04
64664.71        139553.16        137962.62  California  107404.34
75328.87        144135.98        134050.07     Florida  105733.54
72107.60        127864.55        353183.81    New York  105008.31
66051.52        182645.56        118148.20     Florida  103282.38
65605.48        153032.06        107138.38    New York  101004.64
61994.48        115641.28         91131.24     Florida   99937.59
61136.38        152701.92         88218.23    New York   97483.56
63408.86        129219.61         46085.25  California   97427.84
55493.95        103057.49        214634.81     Florida   96778.92
46426.07        157693.92        210797.67  California   96712.80
46014.02         85047.44        205517.64    New York   96479.51
28663.76        127056.21        201126.82     Florida   90708.19
44069.95         51283.14        197029.42  California   89949.14
20229.59         65947.93        185265.10    New York   81229.06
38558.51         82982.09        174999.30  California   81005.76
28754.33        118546.05        172795.67  California   78239.91
27892.92         84710.77        164470.71     Florida   77798.83
23640.93         96189.63        148001.11  California   71498.49
15505.73        127382.30         35534.17    New York   69758.98
22177.74        154806.14         28334.72  California   65200.33
1000.23         124153.04          1903.93    New York   64926.08
1315.46         115816.21        297114.46     Florida   49490.75
0.00            135426.92             0.00  California   42559.73
542.05           51743.15             0.00    New York   35673.41
0.00            116983.80         45173.06  California   14681.40

In [140]:
############ encoder using label encoder from sklearn library #############
le = LabelEncoder()

df['State'] = le.fit_transform(df['State'])
df = df.reset_index()


In [141]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [142]:
X = df.drop(['Profit'], axis=1)

In [143]:
y = df[['Profit']]

In [ ]:
X = X.to_numpy()
X

In [ ]:
y = y.to_numpy()
y

In [10]:
ones = np.ones((X.shape[0],1))
ones
Xbar = np.concatenate((ones,X),axis=1)
Xbar

array([[1.0000000e+00, 1.6534920e+05, 1.3689780e+05, 4.7178410e+05,
        2.0000000e+00],
       [1.0000000e+00, 1.6259770e+05, 1.5137759e+05, 4.4389853e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.5344151e+05, 1.0114555e+05, 4.0793454e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.4437241e+05, 1.1867185e+05, 3.8319962e+05,
        2.0000000e+00],
       [1.0000000e+00, 1.4210734e+05, 9.1391770e+04, 3.6616842e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.3187690e+05, 9.9814710e+04, 3.6286136e+05,
        2.0000000e+00],
       [1.0000000e+00, 1.3461546e+05, 1.4719887e+05, 1.2771682e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.3029813e+05, 1.4553006e+05, 3.2387668e+05,
        1.0000000e+00],
       [1.0000000e+00, 1.2054252e+05, 1.4871895e+05, 3.1161329e+05,
        2.0000000e+00],
       [1.0000000e+00, 1.2333488e+05, 1.0867917e+05, 3.0498162e+05,
        0.0000000e+00],
       [1.0000000e+00, 1.0191308e+05, 1.1059411e+05, 2.2916095e+05,
        1.00

In [11]:
X_train, X_test, y_train, y_test = train_test_split(Xbar,y,train_size=0.8, test_size=0.2, random_state=42)


In [ ]:
A = np.dot(X_train.T,X_train)
A
b = np.dot(X_train.T,y_train)
b

array([[4.62606882e+06],
       [4.35763997e+11],
       [5.64475199e+11],
       [1.23622749e+12],
       [4.86493900e+06]])

In [13]:
w = np.dot(np.linalg.pinv(A),b)
w

array([[ 5.40807170e+04],
       [ 8.03794652e-01],
       [-6.79102293e-02],
       [ 3.12605899e-02],
       [-1.68203098e+01]])

In [14]:
def calculate(prediction, actual):
    SSre = np.sum((actual - prediction)**2)
    SSmean = np.sum((actual - np.mean(actual))**2)
    R2_score = 1 - SSre/SSmean
    return R2_score

prediction = np.dot(X_test,w)
prediction

array([[126720.6615046 ],
       [ 84909.08965155],
       [ 98890.31857357],
       [ 46479.3124175 ],
       [129113.18316915],
       [ 50968.88404243],
       [109015.01627007],
       [100893.57078599],
       [ 97713.73823976],
       [113085.59057559]])

In [15]:
R2_score = calculate(prediction,y_test)
R2_score

0.9000614253465224

In [ ]:
######## Compare with library
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train,y_train)

y_prediction = lr.predict(X_test)
y_prediction


array([[126720.66150723],
       [ 84909.08961913],
       [ 98890.31854876],
       [ 46479.31240248],
       [129113.18318813],
       [ 50968.88397762],
       [109015.01626802],
       [100893.57078084],
       [ 97713.73821431],
       [113085.59056068]])

In [17]:
from sklearn.metrics import r2_score

score = r2_score(y_test,y_prediction)
score

0.9000614254946251